import { ClassViewer } from './components/ClassViewer';
import { DndClass } from './types/index';
import './App.css';

// This is where you would put your class data
// Replace this with your actual class information
const sampleClass: DndClass = {
  id: 'kineticist_001',
  name: 'Kineticist',
  description: 'A conduit of elemental energy, shaping fire, air, water, earth, shadow, radiance, and more into kinetic blasts and infusions.',
  hitDice: 8,
  primaryAttribute: 'constitution',
  attributes: {
    strength: 10,
    dexterity: 14,
    constitution: 16,
    intelligence: 12,
    wisdom: 12,
    charisma: 8,
  },
  abilities: [
    {
      name: 'Subclass Choice',
      description: 'Choose a subclass: Shadow Weaver, Light Bearer, or Nature\'s Wrath. Your subclass adds an elemental option and grants later features.',
      minLevel: 1,
    },
    {
      name: 'Elemental Gate',
      description: 'Choose one primary element from your available list. This choice is permanent and determines the damage types available to your blasts.',
      minLevel: 1,
    },
    {
      name: 'Kinetic Blast',
      description: 'Make a ranged or melee kinetic impulse attack using your proficiency bonus plus Constitution modifier. Damage improves as you deepen mastery.',
      minLevel: 1,
    },
    {
      name: 'Elementalism',
      description: 'Cast the elementalism cantrip without somatic components while you have at least one hand free.',
      minLevel: 1,
    },
    {
      name: 'Unarmored Defense',
      description: 'While not wearing armor and not using a shield, your AC is 10 + Dexterity modifier + Constitution modifier.',
      minLevel: 1,
    },
    {
      name: 'Wild Talents',
      description: 'Channel extra effects into your Kinetic Blast by accepting burn, unlocking infusions and wild talents.',
      minLevel: 2,
    },
    {
      name: 'Burn',
      description: 'Accept burn points up to the higher of your Constitution modifier or proficiency bonus. Burn reduces your maximum hit points until your next long rest.',
      minLevel: 2,
    },
    {
      name: 'Burn Reduction (Channeling)',
      description: 'Reduce burn cost using bonus actions or actions, at the cost of movement or action economy.',
      minLevel: 2,
    },
    {
      name: 'Gate Expansion',
      description: 'At 3rd, 7th, 10th, and 15th levels select either Deepen Mastery or Elemental Reach for your gates.',
      minLevel: 3,
    },
    {
      name: 'Kinetic Surge',
      description: 'When you take the Attack action, make two Kinetic Blasts instead of one.',
      minLevel: 5,
    },
    {
      name: 'Kinetic Transcendence',
      description: 'Your Kinetic Blast and damaging elementalism attacks count as magical for overcoming resistance and immunity.',
      minLevel: 6,
    },
    {
      name: 'Kinetic Durability',
      description: 'When you accept burn as part of an attack, gain temporary hit points equal to your Constitution modifier.',
      minLevel: 6,
    },
    {
      name: 'Empower Infusion',
      description: 'Once per turn, roll damage twice and use the higher result for a Kinetic Blast. Recharge by accepting 2 burn points.',
      minLevel: 7,
    },
    {
      name: 'Kinetic Momentum',
      description: 'When you accept burn on an attack, gain a short-duration movement bonus, jump boost, or movement through creatures.',
      minLevel: 9,
    },
    {
      name: 'Quicken Infusion',
      description: 'Use Kinetic Blast as a bonus action once per turn for half damage and recharge it by accepting 1 burn point.',
      minLevel: 10,
    },
    {
      name: 'Overcharge',
      description: 'Overcharge Kinetic Blast for advantage on the attack roll, maximized damage, and one extra wild talent with no burn cost.',
      minLevel: 11,
    },
    {
      name: 'Elemental Overflow',
      description: 'While you have burn, gain increasing bonuses to attacks, damage, AC, saves, and elemental resistances.',
      minLevel: 13,
    },
    {
      name: 'Internal Buffer',
      description: 'Spend buffer points to avoid burn on impulses and regain a buffer point once per short rest.',
      minLevel: 14,
    },
    {
      name: 'Composite Mastery',
      description: 'Reduce the burn cost of combined wild talents and increase your maximum burn points per attack.',
      minLevel: 17,
    },
    {
      name: 'Kinetic Apotheosis',
      description: 'Enter a 1-minute apotheosis that automatically empowers and quickens blasts, grants resistances, and lets Overcharge ignore backlash.',
      minLevel: 18,
    },
    {
      name: 'True Gate',
      description: 'Gain permanent elemental resistances, more burn capacity, and once per long rest use Overcharge without burn cost or backlash.',
      minLevel: 20,
    },
  ],
  infusions: [
    {
      name: 'Extended Range',
      description: 'Your kinetic blast range increases to 120 feet.',
      element: 'universal',
      blastType: 'Any',
      burnCost: 1,
      minLevel: 2,
    },
    {
      name: 'Kinetic Blade',
      description: 'Form a light or one-handed weapon of pure energy that deals your blast damage die plus Constitution modifier.',
      element: 'universal',
      blastType: 'Any',
      burnCost: 1,
      minLevel: 2,
    },
    {
      name: 'Exploding Arrows',
      description: 'Enhance a ranged weapon attack so the projectile deals extra elemental damage and explodes to nearby creatures.',
      element: 'universal',
      blastType: 'Any',
      burnCost: 1,
      minLevel: 2,
    },
    {
      name: 'Bowling Infusion',
      description: 'Your blast knocks a foe prone on a failed Strength save.',
      element: 'earth',
      blastType: 'Earth, Holyground, Magma, Metal, Mud',
      burnCost: 1,
      minLevel: 3,
    },
    {
      name: 'Burning Infusion',
      description: 'Ignite a target; it takes your kinetic blast damage at the end of its turn until the fire is extinguished.',
      element: 'fire',
      blastType: 'Blue flame, Fire, Green flame, Magma, Plasma',
      burnCost: 1,
      minLevel: 3,
    },
    {
      name: 'Chilling Infusion',
      description: 'A failed Constitution save causes the target to become staggered.',
      element: 'water',
      blastType: 'Cold, Blizzard',
      burnCost: 1,
      minLevel: 3,
    },
    {
      name: 'Dazzling Infusion',
      description: 'A failed Wisdom save blinds the target until the end of its next turn.',
      element: 'fire',
      blastType: 'Blue flame, Fire, Green flame, Plasma, Radiant',
      burnCost: 1,
      minLevel: 3,
    },
    {
      name: 'Dampening Infusion',
      description: 'Your blast blinds a target on a failed Wisdom save.',
      element: 'shadow',
      blastType: 'Green flame, Shadow',
      burnCost: 1,
      minLevel: 3,
    },
    {
      name: 'Magnetic Infusion',
      description: 'The next weapon attack against the target has advantage.',
      element: 'lightning',
      blastType: 'Electric, Metal, Plasma',
      burnCost: 1,
      minLevel: 3,
    },
    {
      name: 'Pushing Infusion',
      description: 'A failed save pushes the target 10 feet away from you.',
      element: 'thunder',
      blastType: 'Air',
      burnCost: 1,
      minLevel: 3,
    },
    {
      name: 'Pulling Infusion',
      description: 'A failed Strength save pulls the target 10 feet closer to you.',
      element: 'shadow',
      blastType: 'Shadow',
      burnCost: 1,
      minLevel: 3,
    },
    {
      name: 'Slick Infusion',
      description: 'Create slippery difficult terrain that forces Dexterity checks or causes creatures to fall prone.',
      element: 'water',
      blastType: 'Water, Ice',
      burnCost: 1,
      minLevel: 3,
    },
    {
      name: 'Thundering Infusion',
      description: 'A failed Wisdom save deafens creatures until the end of their next turn.',
      element: 'air',
      blastType: 'Thunderstorm',
      burnCost: 1,
      minLevel: 3,
    },
    {
      name: 'Venom Infusion',
      description: 'Your target takes ongoing poison damage equal to your Constitution modifier.',
      element: 'poison',
      blastType: 'Acid, Poison, Poisonmist',
      burnCost: 2,
      minLevel: 3,
    },
    {
      name: 'Honed Arrows',
      description: 'Improve the accuracy of a ranged attack from your kinetic blast or kinetic blade.',
      element: 'force',
      blastType: 'Any',
      burnCost: 1,
      minLevel: 3,
    },
    {
      name: 'Rare-Metal Infusion',
      description: 'Infuse your attack to ignore resistances or improve the damage of certain weapon attacks.',
      element: 'force',
      blastType: 'Any',
      burnCost: 1,
      minLevel: 3,
    },
    {
      name: 'Rending Arrows',
      description: 'Your blast-imbued arrow strikes with extra cutting power, ignoring some resistances.',
      element: 'force',
      blastType: 'Any',
      burnCost: 1,
      minLevel: 3,
    },
    {
      name: 'Chain Arrows',
      description: 'Your hit blast can jump to nearby creatures, chaining additional targets for half damage.',
      element: 'universal',
      blastType: 'Unaltered blasts',
      burnCost: 3,
      minLevel: 15,
    },
    {
      name: 'Cloud',
      description: 'Create a cloud that damages anyone who enters it or ends their turn inside it.',
      element: 'air',
      blastType: 'Blizzard, Poisonmist, Sandstorm, Steam, Thunderstorm',
      burnCost: 2,
      minLevel: 7,
      prerequisites: 'Extended Range',
      duration: 'Constitution modifier rounds',
    },
    {
      name: 'Cyclone',
      description: 'Deal blast damage to all creatures within 20 feet; Dexterity save for half.',
      element: 'air',
      blastType: 'Air, Blizzard, Sandstorm, Thunderstorm',
      burnCost: 2,
      minLevel: 7,
    },
    {
      name: 'Darkness Infusion',
      description: 'Create magical darkness around a creature hit by your blast.',
      element: 'shadow',
      blastType: 'Green flame, Shadow',
      burnCost: 2,
      minLevel: 7,
      prerequisites: 'Dampening Infusion',
      duration: 'Constitution modifier rounds',
    },
    {
      name: 'Deadly Earth',
      description: 'Infuse the ground to create a damaging difficult terrain zone.',
      element: 'earth',
      blastType: 'Earth, Holyground, Magma, Metal, Mud',
      burnCost: 2,
      minLevel: 7,
      prerequisites: 'Extended Range',
      duration: 'Constitution modifier rounds',
    },
    {
      name: 'Detonation',
      description: 'Explode your kinetic energy outward, damaging all creatures within 20 feet.',
      element: 'fire',
      blastType: 'Blue flame, Fire, Green flame, Plasma',
      burnCost: 3,
      minLevel: 7,
    },
    {
      name: 'Eruption',
      description: 'Create a pillar of flame that deals extra damage to the target and nearby creatures.',
      element: 'fire',
      blastType: 'Blue flame, Fire, Green flame, Magma, Plasma, Steam',
      burnCost: 3,
      minLevel: 7,
      prerequisites: 'Extended Range',
    },
    {
      name: 'Tremor Infusion',
      description: 'Send tremors through the ground to damage ground-based creatures.',
      element: 'earth',
      blastType: 'Earth',
      burnCost: 2,
      minLevel: 7,
    },
    {
      name: 'Blade Whirlwind',
      description: 'Swing your kinetic blade around you in a whirlwind attack.',
      element: 'universal',
      blastType: 'Any',
      burnCost: 2,
      minLevel: 11,
      prerequisites: 'Kinetic Blade',
    },
    {
      name: 'Grappling Infusion',
      description: 'Grapple a target with your blast energy and restrain it until it escapes.',
      element: 'universal',
      blastType: 'Any',
      burnCost: 2,
      minLevel: 11,
      prerequisites: 'Dexterity saving throw',
    },
    {
      name: 'Vampiric Infusion',
      description: 'Heal for half the damage dealt by your blast.',
      element: 'necrotic',
      blastType: 'Green flame, Shadow',
      burnCost: 3,
      minLevel: 11,
    },
    {
      name: 'Foxfire Infusion',
      description: 'Mark or burn a target with fiery or radiant energy for ongoing effects.',
      element: 'radiant',
      blastType: 'Fire or Radiant',
      burnCost: 1,
      minLevel: 3,
    },
    {
      name: 'Guardian Infusion',
      description: 'Create protective energy that grants defensive benefits for you or allies.',
      element: 'radiant',
      blastType: 'Plasma, Radiant',
      burnCost: 2,
      minLevel: 7,
    },
    {
      name: 'Greater Venom Infusion',
      description: 'Improve Venom Infusion to increase potency and impose disadvantage on the save.',
      element: 'poison',
      blastType: 'Acid, Poison, Poisonmist',
      burnCost: 2,
      minLevel: 7,
      prerequisites: 'Venom Infusion',
    },
  ],
  subclasses: [
    {
      id: 'shadow_weaver_001',
      name: 'Shadow Weaver',
      description: 'Your kinetic gate taps the Plane of Shadow. You specialize in hit-and-run tactics, draining life and slashing from darkness.',
      abilities: [
        {
          name: 'Shadow Weaver',
          description: 'Your kinetic gate taps the Plane of Shadow. You specialize in hit-and-run tactics, draining life and slashing from darkness.\n\nKinetic Blast Upgrades: Deals slashing or necrotic damage (choose per attack). Range: 60 ft ranged / 5 ft melee\n\nShadow Veil: You gain proficiency in Stealth (or expertise if already proficient). While in dim light or darkness, you can Hide as a bonus action if you have cover or are lightly obscured, and you have advantage on Dexterity (Stealth) checks in those conditions.',
          minLevel: 3,
        },
        {
          name: 'Weave the Darkness',
          description: 'Bonus Action, accept 1 Burn: Swirling shadows cloak you until the start of your next turn:\n• You gain resistance to necrotic damage and to bludgeoning, piercing, and slashing from nonmagical attacks.\n• Opportunity attacks against you have disadvantage.\n• Your movement doesn\'t provoke opportunity attacks from creatures that you hit with your Kinetic Blast attack.',
          minLevel: 3,
        },
        {
          name: 'Shadow Teleport',
          description: 'As a bonus action while you are in dim light or darkness, you can accept 1 point of burn to magically teleport up to 60 feet to an unoccupied space you can see that is also in dim light or darkness. This teleportation does not provoke opportunity attacks.\n\nIf you end the teleport in dim light or darkness, the first Kinetic Blast you make before the end of your turn has advantage on the attack roll (this does not stack with Empower Infusion).',
          minLevel: 7,
        },
        {
          name: 'Siphon Life',
          description: 'Whenever you hit a creature with your Kinetic Blast using necrotic damage, you drain its life force. You regain hit points equal to your Constitution modifier (minimum 1).\n\nYou can choose to accept 1 additional point of burn when you hit to double the hit points regained (2 × your Constitution modifier).',
          minLevel: 10,
        },
        {
          name: 'Umbral Sovereign',
          description: 'You have become a true sovereign of the Plane of Shadow. Shadows bend to your will as naturally as breathing.\n\nPassive Benefit: You are always treated as being in dim light or darkness for the purposes of every Shadow Weaver feature (even in bright light). Harmless wisps of shadow constantly swirl around you in a 10-foot radius.\n\nUmbral Sovereign (Action, accept 3 Burn): Enter a state of Umbral Sovereignty for 1 minute (once per long rest). You can recharge this use at any time by accepting 6 points of burn (no action required).\n\nWhile in Umbral Sovereignty, you gain the following:\n• You are invisible while in dim light or darkness.\n• You can use Shadow Teleport as a bonus action with no burn cost and at double range (120 feet). You can make an opportunity creature of your size or smaller you pass through.',
          minLevel: 15,
        },
      ],
    },
  ],
  armor: ['Light armor'],
  weapons: ['Simple weapons'],
  skills: ['Acrobatics', 'Arcana', 'Athletics', 'Nature', 'Perception', 'Stealth', 'Survival'],
  createdAt: Date.now(),
  updatedAt: Date.now(),
};

function App() {
  return <ClassViewer dndClass={sampleClass} />;
}

export default App;